### ISSUE TITLE
Game: Console Command Reference & User Guide

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/BGS-Handbook#9]
The console command reference is far more developed on the Skyrim wiki than Fallout 4. Many of these commands are the same in Fallout 4 as they are carryovers from Skyrim. We need someone to verify the console command list for Fallout 4 and recycle as much of the Skyrim reference as possible. Something the Fallout 4 wiki has that Skyrim does not is a page for the **console menu** itself. For both games there are a number of INI settings related to this menu. These should be mentioned for both games.

### Wiki
- [ ] Turn the main console command reference page into a console user guide.
- [ ] Establish a template or style guideline for console command pages.
- [ ] Explain how batch commands with standard text files works.
- [ ] Explain PRID on the console menu and batch files.

## Skyrim
https://ck.uesp.net/wiki/Console
https://ck.uesp.net/wiki/Category:Console_Commands

**TODO**
- [ ] Turn the main console command reference page into a console user guide.
- [ ] Add `Console` menu page.
- [ ] Add related INI settings.

## Fallout 4
https://falloutck.uesp.net/wiki/Console
https://falloutck.uesp.net/wiki/Console_Command_Reference

**TODO**
- [ ] Turn the main console command reference page into a console user guide.
- [ ] Add missing console command pages.
- [ ] Add related INI settings.

##### INI Settings
https://falloutck.uesp.net/wiki/Initialization_File
These are only a few. A complete list should be formed. The list below is relevant to Fallout 4.
```ini
[Menu]
iConsoleSizeScreenPercent=60
iConsoleTextSize=14
iConsoleHistoryCharBufferSize=1048576
iConsoleSelectedRefColor=335544575
rDebugTextColor=255,251,233
uUISaveBatchLoadInterval=125
bUseConsoleHotkeys=0
sConsoleNetworkPath=\\bgs\f4\users\
sConsoleDefaultINI=Fallout4ConsoleDefault.ini
sConsoleINI=Fallout4Console.ini
rConsoleHistoryTextColor=153,153,153
rConsoleTextColor=255,255,255
```

##### Commands
The console command reference page should explain what console commands are and how they are used. The page should outright explain the core commands. The list below is relevant to Fallout 4.
https://gist.github.com/reg2k/bad5567d30787067dcaa42ba948ce87e
```
help
SetConsoleOutputFile (scof)
RunConsoleBatch (bat)
ClearConsole (clear)
```
```
PickRefByID (PRID)
PickLastRef (PLR)
PickNextRef (PNR)
PickNextActor (PNA)
PickNextActor (PNA)
```
```
SaveINI
RefreshINI
```
```
SaveGame <filename>
LoadGame <filename>
```

**Comment by Scrivener07** [comment]
This is the Bethesda console command notation. 
https://ck.uesp.net/wiki/Activate

**Note on syntax:** 
- Italics = object that's acted on
- Bold = function name
- [Brackets] = optional field
- "rec" = record
- "bin" = binary
